codebuild_cache_bucket_name="apprunner-cache-YYYYMMDD-identifier"
aws_region="us-east-1"
stack="apprunner-workshop"
aws_ecr="petclinic"
aws_profile="default"
source_repo_name="petclinic"
source_repo_branch="master"
image_repo_name="petclinic"